{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This code (will be) set up to generate a forecasted impact map of a specified area.\n",
    "The area in the example case is Houston, TX\n",
    "The inundation extent is sourced from the National Water Model forecast. \n",
    "Depth model is calculated from the inundation extent and the national 3m DEM\n",
    "The impact map is calculated from the depth and the CDC SVI scores at the census tract scale. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# edit code so that it runs automatically every hour\n",
    "# use python.12.4 kernel\n",
    "# THIS IS A WORK IN PROGRESS"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Currently, the dependencies require numpy <2, so make sure your numpy package matches that requirement. If it does, skip the next two steps"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# currently we need numpy <2. So downgrade numpy to 1.19.5\n",
    "%pip uninstall numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install 'numpy<2'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Import packages and set the paths to the working directory and input files\n",
    "TO DO: \n",
    "1. Replace the directory path with the path to the folder you want to work in\n",
    "2. Replace dem_name with path to the dem you want to use (as a tif) \n",
    "3. Replace the inund_polygon with path to the area extent you want to map (as a .shp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "New folder created at: C:/Users/Lyn/Documents/Programming/Python_codes/fwdet/Forecast_test_5day/5dayforecast20240705_132212\n",
      "Current Working Directory:  C:\\Users\\Lyn\\Documents\\Programming\\Python_codes\\fwdet\\Forecast_test_5day\\5dayforecast20240705_132212\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\900844986.py\", line 36, in <cell line: 36>\n",
      "    arcpy.CreateFileGDB_management(out_folder_path = infolder, out_name='geodatabase.gdb')\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 25912, in CreateFileGDB\n",
      "    retval = convertArcObjectToPythonObject(gp.CreateFileGDB_management(*gp_fixargs((out_folder_path, out_name, out_version), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\900844986.py\", line 36, in <cell line: 36>\n",
      "    arcpy.CreateFileGDB_management(out_folder_path = infolder, out_name='geodatabase.gdb')\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 25912, in CreateFileGDB\n",
      "    retval = convertArcObjectToPythonObject(gp.CreateFileGDB_management(*gp_fixargs((out_folder_path, out_name, out_version), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    }
   ],
   "source": [
    "# Import packages\n",
    "import os\n",
    "import arcpy\n",
    "from datetime import datetime\n",
    "\n",
    "# Format the current datetime as a string in the desired format (e.g., YYYYMMDD_HHMMSS)\n",
    "datetime = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "\n",
    "\n",
    "# Replace 'path/to/your/directory' with the path to your desired working directory\n",
    "directory = 'C:/Users/Lyn/Documents/Programming/Python_codes/fwdet/Forecast_test_5day/'\n",
    "\n",
    "# Create a new folder within the current working directory\n",
    "resultfolder = \"5dayforecast\"+datetime\n",
    "os.makedirs(os.path.join(directory, resultfolder), exist_ok=True)\n",
    "print(f\"New folder created at: {os.path.join(directory, resultfolder)}\")\n",
    "infolder = directory+resultfolder+'/'\n",
    "\n",
    "\n",
    "# set up input variables\n",
    "dem_name = 'C:/Users/Lyn/Documents/Programming/Python_codes/fwdet/Forecast_test_5day/Houston_DEM.tif'\n",
    "inund_polygon = 'C:/Users/Lyn/Documents/Programming/Python_codes/fwdet/Forecast_test_5day/clipped_extent.shp'\n",
    "\n",
    "\n",
    "# Set the working directory\n",
    "os.chdir(infolder)\n",
    "# Verify the current working directory\n",
    "print(\"Current Working Directory: \", os.getcwd())\n",
    "\n",
    "# set up input and output variables\n",
    "arcpy.env.overwriteOutput = True\n",
    "\n",
    "# make a geodatabase within the infolder   \n",
    "gdb_path = infolder \n",
    "# Create the geodatabase\n",
    "arcpy.CreateFileGDB_management(out_folder_path = infolder, out_name='geodatabase.gdb')\n",
    "#workspace\n",
    "ws = arcpy.env.workspace = infolder"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Query the NWM 5 day inundation exent. This section will download it as a shapefile, merge polygons, and prepare for depth calculaiton"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\1076500937.py\", line 3, in <cell line: 3>\n",
      "    import geopandas as gpd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\__init__.py\", line 1, in <module>\n",
      "    from geopandas._config import options\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 109, in <module>\n",
      "    default_value=_default_use_pygeos(),\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 95, in _default_use_pygeos\n",
      "    import geopandas._compat as compat\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_compat.py\", line 8, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\__init__.py\", line 54, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\1076500937.py\", line 3, in <cell line: 3>\n",
      "    import geopandas as gpd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\__init__.py\", line 1, in <module>\n",
      "    from geopandas._config import options\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 109, in <module>\n",
      "    default_value=_default_use_pygeos(),\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 95, in _default_use_pygeos\n",
      "    import geopandas._compat as compat\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_compat.py\", line 8, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\__init__.py\", line 77, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\1076500937.py\", line 3, in <cell line: 3>\n",
      "    import geopandas as gpd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\__init__.py\", line 1, in <module>\n",
      "    from geopandas._config import options\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 109, in <module>\n",
      "    default_value=_default_use_pygeos(),\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 95, in _default_use_pygeos\n",
      "    import geopandas._compat as compat\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_compat.py\", line 8, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\__init__.py\", line 77, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\ops\\__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\computation\\expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\computation\\check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\numexpr\\__init__.py\", line 24, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\1076500937.py\", line 3, in <cell line: 3>\n",
      "    import geopandas as gpd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\__init__.py\", line 1, in <module>\n",
      "    from geopandas._config import options\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 109, in <module>\n",
      "    default_value=_default_use_pygeos(),\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_config.py\", line 95, in _default_use_pygeos\n",
      "    import geopandas._compat as compat\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\geopandas\\_compat.py\", line 8, in <module>\n",
      "    import pandas as pd\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\__init__.py\", line 77, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\arrays\\masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\core\\nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Roaming\\Python\\Python39\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\bottleneck\\__init__.py\", line 7, in <module>\n",
      "    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                            geometry feature_id  \\\n",
      "0  POLYGON ((-96.70638 32.29966, -96.70670 32.299...    1446524   \n",
      "1  MULTIPOLYGON (((-98.91162 27.26558, -98.91162 ...     325213   \n",
      "2  MULTIPOLYGON (((-98.92063 27.22029, -98.92062 ...     325213   \n",
      "3  MULTIPOLYGON (((-98.92538 27.20926, -98.92538 ...     325213   \n",
      "4  MULTIPOLYGON (((-98.91939 27.25465, -98.91949 ...     325213   \n",
      "\n",
      "   streamflow_cfs           reference_time              update_time  oid  \n",
      "0          410.71  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    1  \n",
      "1            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    2  \n",
      "2            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    3  \n",
      "3            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    4  \n",
      "4            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    5  \n",
      "                                            geometry feature_id  \\\n",
      "0  POLYGON ((-96.70638 32.29966, -96.70670 32.299...    1446524   \n",
      "1  MULTIPOLYGON (((-98.91162 27.26558, -98.91162 ...     325213   \n",
      "2  MULTIPOLYGON (((-98.92063 27.22029, -98.92062 ...     325213   \n",
      "3  MULTIPOLYGON (((-98.92538 27.20926, -98.92538 ...     325213   \n",
      "4  MULTIPOLYGON (((-98.91939 27.25465, -98.91949 ...     325213   \n",
      "\n",
      "   streamflow_cfs           reference_time              update_time  oid  \n",
      "0          410.71  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    1  \n",
      "1            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    2  \n",
      "2            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    3  \n",
      "3            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    4  \n",
      "4            8.12  2024-07-05 06:00:00 UTC  2024-07-05 12:34:25 UTC    5  \n"
     ]
    }
   ],
   "source": [
    "# query the NOAA API for the most recent flood predictions\n",
    "import requests\n",
    "import geopandas as gpd\n",
    "\n",
    "# Construct the query URL\n",
    "# To change the query, you can go to https://maps.water.noaa.gov/server/rest/services/nwm\n",
    "# Then select the link you want, copy it here, and add /0/query to the end\n",
    "# e.g. https://link_to_service/0/query\n",
    "query_url = \"https://maps.water.noaa.gov/server/rest/services/nwm/mrf_gfs_5day_max_inundation_extent/MapServer/0/query\"\n",
    "params = {\n",
    "    'where': '1=1',\n",
    "    'outFields': '*',\n",
    "    'outSR': '4326',  # Specify output spatial reference if needed\n",
    "    'f': 'geojson',  # Request geojson output\n",
    "    'returnGeometry': 'true'\n",
    "}\n",
    "# Make the request\n",
    "response = requests.get(query_url, params=params)\n",
    "\n",
    "\n",
    "# Check if the server is running correctly. A response of 500 means there is a server error. \n",
    "if response.status_code == 200:\n",
    "    try:\n",
    "        # Attempt to convert the response to a GeoDataFrame\n",
    "        predictions = gpd.GeoDataFrame.from_features(response.json(), crs=\"EPSG:4326\")\n",
    "        print(predictions.head())\n",
    "    except ValueError as e:\n",
    "        # Handle JSON decoding errors\n",
    "        print(f\"Error decoding JSON: {e}\")\n",
    "else:\n",
    "    # The request failed; print the status code and response text\n",
    "    print(f\"Request failed with status {response.status_code}: {response.text}\")\n",
    "\n",
    "\n",
    "\n",
    "# Convert to GeoDataFrame\n",
    "predictions = gpd.GeoDataFrame.from_features(response.json(), crs=\"EPSG:4326\")\n",
    "print(predictions.head())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install numpy --upgrade"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "clip the predictions to the dem extent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# clip the predictions to the extent of interest - defined by the dem_name above\n",
    "\n",
    "import geopandas as gpd\n",
    "import rasterio\n",
    "from shapely.geometry import box\n",
    "\n",
    "\n",
    "# Open the DEM file with rasterio\n",
    "with rasterio.open(dem_name) as dem:\n",
    "    # Read the entire file into a numpy array\n",
    "    bounds = dem.bounds\n",
    "\n",
    "\n",
    "# Create a bounding box polygon from the DEM bounds\n",
    "bounding_box_polygon = box(*bounds)\n",
    "\n",
    "# Clip the predictions GeoDataFrame to the bounding box\n",
    "clipped_predictions = gpd.clip(predictions, bounding_box_polygon)\n",
    "predictions = clipped_predictions\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "20240705_132340\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\1087914008.py:11: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.\n",
      "  predictions.to_file(file_name)\n"
     ]
    }
   ],
   "source": [
    "# export predictions as a shapefile\n",
    "\n",
    "from datetime import datetime\n",
    "# Format the current datetime as a string in the desired format (e.g., YYYYMMDD_HHMMSS)\n",
    "datetime = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "\n",
    "print(datetime)\n",
    "\n",
    "# Export GeoDataFrame as a Shapefile\n",
    "file_name = infolder+\"/5day_inundationextent_{datetime}.shp\"\n",
    "predictions.to_file(file_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# If predictions is empty, print a message and exit the script\n",
    "import sys\n",
    "if predictions.empty:\n",
    "    print(\"No flood predictions in this area found.\")\n",
    "    sys.exit(0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## FWDET2.1 calculates depth map from inundation extent\n",
    "### Written by Dr.Sagy Cohen"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# use kernel arcgispro-py3 (python 3.9.16)\n",
    "import arcpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "#clip_dem = '' #[Optional] - If empty, the clip_dem will be calculated with the Clip_management function\n",
    "#cost_raster ='' #[Optional] - If empty, the CostRaster will be calculated below\n",
    "WaterDepthOutput = 'WaterDepth_i10_s0p5'\n",
    "iterations = 10\n",
    "SlopeFiltering = True\n",
    "SlopeThreshold = 0.5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.0 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\traitlets\\config\\application.py\", line 982, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Lyn\\AppData\\Local\\Temp\\ipykernel_17296\\4090663469.py\", line 13, in <cell line: 13>\n",
      "    arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\management.py\", line 20980, in Clip\n",
      "    retval = convertArcObjectToPythonObject(gp.Clip_management(*gp_fixargs((in_raster, rectangle, out_raster, in_template_dataset, nodata_value, clipping_geometry, maintain_clipping_extent), True)))\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\Resources\\ArcPy\\arcpy\\geoprocessing\\_base.py\", line 512, in <lambda>\n",
      "    return lambda *args: val(*gp_fixargs(args, True))\n",
      "  File \"c:\\Users\\Lyn\\AppData\\Local\\ESRI\\conda\\envs\\arcgispro-py3-clone\\lib\\site-packages\\pyarrow\\__init__.py\", line 62, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    }
   ],
   "source": [
    "# clean and create necessary variables\n",
    "dem = arcpy.Raster(dem_name)\n",
    "cell_size = dem.meanCellHeight\n",
    "# Proper string representation of dem extent to be accepted by Clip_management method\n",
    "extent = '{} {} {} {}'.format(dem.extent.XMin, dem.extent.YMin, dem.extent.XMax, dem.extent.YMax)\n",
    "\n",
    "# Dont run these if cost_raster and clip_dem are already defined above\n",
    "cost_raster = (((dem <= 0)*999)+1)\n",
    "cost_raster.save('CostRaster.tif')\n",
    "\n",
    "clip_dem = 'ClipDEM'\n",
    "\n",
    "arcpy.management.Clip(dem, extent, clip_dem, inund_polygon, nodata_value= \"-9999\", clipping_geometry=\"ClippingGeometry\", maintain_clipping_extent=\"NO_MAINTAIN_EXTENT\")\n",
    "clip_dem_ras = arcpy.Raster(clip_dem)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate Boundary Raster\n",
    "arcpy.env.overwriteOutput = True\n",
    "polyline = infolder + '/polyline.shp'\n",
    "arcpy.PolygonToLine_management(inund_polygon, polyline)\n",
    "# Convert polyline to raster\n",
    "with arcpy.EnvManager(snapRaster=clip_dem_ras):\n",
    "    arcpy.conversion.PolylineToRaster(polyline, 'FID', 'linerast15', \"MAXIMUM_LENGTH\", \"NONE\", cell_size)\n",
    "raster_polyline = arcpy.Raster('linerast15')\n",
    "raster_polyline.save(\"rstr_poly\")\n",
    "# The input whose values will be used as the output cell values if the condition is false.\n",
    "inFalseConstant = '#'\n",
    "where_clause = 'VALUE >= 0'\n",
    "#Extract the boundary cells elevation from DEM\n",
    "boundary = arcpy.sa.Con(raster_polyline, dem, inFalseConstant, where_clause)\n",
    "# boundary.save('boundary1')\n",
    "#Smooth boundary raster\n",
    "for i in range(iterations):\n",
    "    OutRasTemp = arcpy.sa.FocalStatistics(boundary, \"Rectangle 5 5 CELL\", 'MEAN', 'DATA')\n",
    "    boundary = arcpy.sa.Con(raster_polyline, OutRasTemp, inFalseConstant, where_clause)\n",
    "    boundary.save('boundary'+str(i+1))\n",
    "#Identify and remove ocean boundary cells\n",
    "OutRasTemp = arcpy.sa.FocalStatistics(dem, 'Circle 2 CELL', 'MINIMUM', 'DATA') \n",
    "whereClause2 = 'VALUE > 0'\n",
    "boundary = arcpy.sa.Con(OutRasTemp, boundary, inFalseConstant, whereClause2)\n",
    "#boundary.save(\"boundaryAfterOcean\")\n",
    "if SlopeFiltering:\n",
    "#calculate topo slope\n",
    "    print('Calculating Slope')\n",
    "    extent_clip = '{} {} {} {}'.format(boundary.extent.XMin, boundary.extent.YMin, boundary.extent.XMax, boundary.extent.YMax)\n",
    "    with arcpy.EnvManager(extent=extent_clip):\n",
    "        out_slope = arcpy.sa.Slope(dem, \"PERCENT_RISE\", 1, \"GEODESIC\", \"METER\")\n",
    "        out_slope.save(\"Slope_m\")\n",
    "#Remove erroneous boundary cells \n",
    "    whereClause_slope = 'VALUE > ' + str(SlopeThreshold)\n",
    "    boundary = arcpy.sa.Con(out_slope, boundary, inFalseConstant, whereClause_slope)\n",
    "boundary.save(\"boundFinal\")\n",
    "print('Finished calculating the boundary raster')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate water depth \n",
    "\n",
    "MULTIPLIER = 10000\n",
    "boundary_int = arcpy.sa.Int(boundary * MULTIPLIER)\n",
    "#boundary_int.save(\"boundary_int\")\n",
    "print('Running cost allocation')\n",
    "with arcpy.EnvManager(snapRaster=None, extent=\"DEFAULT\", mask=clip_dem):\n",
    "    cost_alloc = arcpy.sa.CostAllocation(boundary_int, cost_raster, '#', '#', 'Value')\n",
    "\n",
    "# Divide the result from the cost allocation function using the same constant used to create the integer\n",
    "# representation of the boundary\n",
    "cost_alloc = arcpy.sa.Float(cost_alloc) / MULTIPLIER\n",
    "print('Cost Allocation raster generated')\n",
    "print('Calculating estimated water depth')\n",
    "water_depth = (cost_alloc - clip_dem_ras)\n",
    "# Remove estimated water depths below 0 and change them to 0\n",
    "water_depth = arcpy.sa.Con(water_depth > 0, water_depth,\"#\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run a low-pass filter\n",
    "# ie smooth the water depth raster\n",
    "print('Running low-pass Filter')\n",
    "water_depth_filtered = arcpy.sa.Filter(water_depth, 'LOW', 'DATA')\n",
    "waterDepthFilter2 = arcpy.sa.Con(clip_dem_ras, water_depth_filtered, '#', 'VALUE > 0')\n",
    "#waterDepthFilter2.save(WaterDepthOutput+'_filtered')\n",
    "print('Finished low-pass Filter calculation')\n",
    "#waterDepthFilter2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Turn the shapefile of the depth map into a raster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Turn the shapefile of the depth map into a raster\n",
    "import os\n",
    "import geopandas as gpd\n",
    "from osgeo import gdal, ogr, osr\n",
    "\n",
    "# Set the working directory\n",
    "os.chdir(infolder)\n",
    "\n",
    "# Read the shapefile using GeoPandas\n",
    "#shapefile = gpd.read_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/svi_data.shp')\n",
    "\n",
    "# Open the shapefile using OGR\n",
    "#input_shp = ogr.Open(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/svi_data.shp')\n",
    "#source_layer = input_shp.GetLayer()\n",
    "#defn = source_layer.GetLayerDefn()\n",
    "\n",
    "# Extract column names\n",
    "column_names = []\n",
    "for n in range(predictions.GetFieldCount()):\n",
    "    fdefn = predictions.GetFieldDefn(n)\n",
    "    column_names.append(fdefn.GetName())\n",
    "\n",
    "# Define output raster location and pixel size\n",
    "output_raster_location = infolder+'svi_raster.tif'\n",
    "pixel_size = 0.0001\n",
    "\n",
    "# Get extent of the source layer\n",
    "xmin, xmax, ymin, ymax = predictions.GetExtent()\n",
    "\n",
    "# Calculate resolution\n",
    "x_res = int(round((xmax - xmin) / pixel_size))\n",
    "y_res = int(round((ymax - ymin) / pixel_size))\n",
    "\n",
    "# Create the target raster file\n",
    "target_ds = gdal.GetDriverByName('GTiff').Create(output_raster_location, x_res, y_res, 1, gdal.GDT_Float32, ['COMPRESS=LZW'])\n",
    "target_ds.SetGeoTransform((xmin, pixel_size, 0, ymax, 0, -pixel_size))\n",
    "\n",
    "# Set projection\n",
    "srs = osr.SpatialReference()\n",
    "srs.ImportFromEPSG(4269)  # EPSG:4269 is NAD83\n",
    "target_ds.SetProjection(srs.ExportToWkt())\n",
    "\n",
    "# Get the raster band and set NoData value\n",
    "band = target_ds.GetRasterBand(1)\n",
    "band.SetNoDataValue(-9999)\n",
    "band.Fill(-9999)\n",
    "\n",
    "# Rasterize the shapefile layer to the raster\n",
    "gdal.RasterizeLayer(target_ds, [1], source_layer, options=['ALL_TOUCHED=TRUE', 'ATTRIBUTE=SVI'])\n",
    "\n",
    "# Close the raster dataset\n",
    "target_ds = None\n",
    "\n",
    "print(\"Rasterization complete!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Run SVI using depth map"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 1: Load the ESRI Geodatabase and Clip the Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import geopandas as gpd\n",
    "from shapely.geometry import box\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import matplotlib.colors as colors\n",
    "import matplotlib.colorbar as colorbar\n",
    "import rasterio\n",
    "from rasterio.features import rasterize\n",
    "from rasterio.plot import show\n",
    "import folium\n",
    "from rasterio.warp import calculate_default_transform, reproject, Resampling\n",
    "from matplotlib.colors import Normalize\n",
    "from rasterio.transform import from_bounds\n",
    "from osgeo import gdal, ogr, osr\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Load the ESRI Geodatabase\n",
    "#gdb_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N/Texas/SVI2022_TEXAS_tract.gdb'\n",
    "gdf = gpd.read_file(gdb_path)\n",
    "\n",
    "# Load the shapefile for your area\n",
    "area_shapefile = inund_polygon #AOI\n",
    "area_gdf = gpd.read_file(area_shapefile)\n",
    "\n",
    "\n",
    "# Reproject the shapefile to match the CRS of the ESRI Geodatabase\n",
    "area_gdf = area_gdf.to_crs(gdf.crs)\n",
    "\n",
    "# Clip the geodatabase data to your area\n",
    "clipped_gdf = gpd.clip(gdf, area_gdf)\n",
    "\n",
    "\n",
    "# Save the clipped data for further processing\n",
    "#clipped_gdf.to_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/clipped_data.shp')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the clipped data\n",
    "#clipped_gdf = gpd.read_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/clipped_data.shp')\n",
    "\n",
    "# Plot the clipped data\n",
    "fig, ax = plt.subplots(figsize=(10, 10))\n",
    "clipped_gdf.plot(ax=ax, edgecolor='k')\n",
    "\n",
    "# Optionally, add the area boundary for reference\n",
    "#area_gdf = gpd.read_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N/AOI/HUC8_Houston4326.shp')\n",
    "#area_gdf.boundary.plot(ax=ax, color='red')\n",
    "\n",
    "plt.title('SVI Data Houston city')\n",
    "plt.xlabel('Longitude')\n",
    "plt.ylabel('Latitude')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 2: Filter and Clean the Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Identify the columns starting with 'F_'\n",
    "flag_columns = [col for col in clipped_gdf.columns if col.startswith('F_')]\n",
    "\n",
    "# Keep geospatial columns (geometry) and flag columns\n",
    "columns_to_keep = ['geometry'] + flag_columns\n",
    "clipped_gdf = clipped_gdf[columns_to_keep]\n",
    "\n",
    "# Function to fill -999 values with the average of neighboring values\n",
    "def fill_missing_values(gdf, columns):\n",
    "    for col in columns:\n",
    "        missing_indices = gdf[gdf[col] == -999].index\n",
    "        for idx in missing_indices:\n",
    "            neighbors = gdf[gdf.geometry.touches(gdf.loc[idx, 'geometry'])]\n",
    "            if not neighbors.empty:\n",
    "                gdf.at[idx, col] = int(np.round(neighbors[col].replace(-999, np.nan).mean()))\n",
    "    return gdf\n",
    "\n",
    "# Fill missing values\n",
    "clipped_gdf = fill_missing_values(clipped_gdf, flag_columns)\n",
    "\n",
    "# Save the cleaned data\n",
    "#clipped_gdf.to_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/cleaned_data.shp')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 3: Calculate the Final SVI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the cleaned data\n",
    "#clipped_gdf = gpd.read_file(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N2/cleaned_data.shp')\n",
    "\n",
    "# Select specific variables for SVI calculation\n",
    "selected_variables = ['F_POV150', 'F_UNEMP', 'F_HBURD', 'F_UNINSUR', 'F_AGE65', 'F_AGE17', 'F_DISABL', 'F_LIMENG', 'F_MUNIT', 'F_MOBILE', 'F_CROWD', 'F_NOVEH', 'F_GROUPQ']\n",
    "clipped_gdf['SVI'] = clipped_gdf[selected_variables].sum(axis=1)\n",
    "\n",
    "# Remove all columns except 'geometry' and 'SVI'\n",
    "clipped_gdf = clipped_gdf[['geometry', 'SVI']]\n",
    "\n",
    "# Visualize the SVI with a legend\n",
    "fig, ax = plt.subplots(figsize=(10, 10))\n",
    "\n",
    "# Number of classes for visualization\n",
    "num_classes = 5\n",
    "cmap = plt.cm.viridis\n",
    "norm = colors.BoundaryNorm(np.linspace(clipped_gdf['SVI'].min(), clipped_gdf['SVI'].max(), num_classes + 1), cmap.N)\n",
    "\n",
    "# Plot the data\n",
    "clipped_gdf.plot(column='SVI', cmap=cmap, linewidth=0.8, ax=ax, edgecolor='0.8', legend=False, norm=norm)\n",
    "\n",
    "# Add color bar\n",
    "sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)\n",
    "sm._A = []\n",
    "cbar = fig.colorbar(sm, ax=ax, fraction=0.026, pad=0.01)\n",
    "cbar.set_label('SVI')\n",
    "\n",
    "plt.title('Social Vulnerability Index (SVI)')\n",
    "plt.xlabel('Longitude')\n",
    "plt.ylabel('Latitude')\n",
    "plt.show()\n",
    "\n",
    "# Save the SVI data\n",
    "clipped_gdf.to_file(infolder+'svi_data.shp')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 4: Build a Raster Map\n",
    "Convert the final SVI data into a raster map with specified cell size and number of classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import geopandas as gpd\n",
    "from osgeo import gdal, ogr, osr\n",
    "\n",
    "# Set the working directory\n",
    "#os.chdir(r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3')\n",
    "\n",
    "# Read the shapefile using GeoPandas\n",
    "shapefile = gpd.read_file(infolder+'svi_data.shp')\n",
    "\n",
    "# Open the shapefile using OGR\n",
    "input_shp = ogr.Open(infolder+'svi_data.shp')\n",
    "source_layer = input_shp.GetLayer()\n",
    "defn = source_layer.GetLayerDefn()\n",
    "\n",
    "# Extract column names\n",
    "column_names = []\n",
    "for n in range(defn.GetFieldCount()):\n",
    "    fdefn = defn.GetFieldDefn(n)\n",
    "    column_names.append(fdefn.GetName())\n",
    "\n",
    "# Define output raster location and pixel size\n",
    "output_raster_location = infolder+'svi_raster.tif'\n",
    "pixel_size = 0.0001\n",
    "\n",
    "# Get extent of the source layer\n",
    "xmin, xmax, ymin, ymax = source_layer.GetExtent()\n",
    "\n",
    "# Calculate resolution\n",
    "x_res = int(round((xmax - xmin) / pixel_size))\n",
    "y_res = int(round((ymax - ymin) / pixel_size))\n",
    "\n",
    "# Create the target raster file\n",
    "target_ds = gdal.GetDriverByName('GTiff').Create(output_raster_location, x_res, y_res, 1, gdal.GDT_Float32, ['COMPRESS=LZW'])\n",
    "target_ds.SetGeoTransform((xmin, pixel_size, 0, ymax, 0, -pixel_size))\n",
    "\n",
    "# Set projection\n",
    "srs = osr.SpatialReference()\n",
    "srs.ImportFromEPSG(4269)  # EPSG:4269 is NAD83\n",
    "target_ds.SetProjection(srs.ExportToWkt())\n",
    "\n",
    "# Get the raster band and set NoData value\n",
    "band = target_ds.GetRasterBand(1)\n",
    "band.SetNoDataValue(-9999)\n",
    "band.Fill(-9999)\n",
    "\n",
    "# Rasterize the shapefile layer to the raster\n",
    "gdal.RasterizeLayer(target_ds, [1], source_layer, options=['ALL_TOUCHED=TRUE', 'ATTRIBUTE=SVI'])\n",
    "\n",
    "# Close the raster dataset\n",
    "target_ds = None\n",
    "\n",
    "print(\"Rasterization complete!\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Caculate the Impact "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 1: read the svi raster and fim raster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rasterio\n",
    "\n",
    "# Define the paths to the raster files - same as the output above\n",
    "svi_raster_path = output_raster_location\n",
    "fim_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/fim_raster.tif'\n",
    "\n",
    "def check_raster_properties(raster_path):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        print(f\"Properties of {raster_path}:\")\n",
    "        print(f\" CRS: {src.crs}\")\n",
    "        print(f\" Cell size: {src.res}\")\n",
    "        print(f\" Width: {src.width}, Height: {src.height}\")\n",
    "        print(f\" Bounds: {src.bounds}\")\n",
    "        print()\n",
    "\n",
    "# Read and check properties of SVI raster\n",
    "check_raster_properties(svi_raster_path)\n",
    "\n",
    "# Read and check properties of FIM raster\n",
    "check_raster_properties(fim_raster_path)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Step 2: Reproject and Resample SVI Raster\n",
    "Skip this if they have same projection and cell size"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##### make sure that the svi map has the same crs and cell size of fim map"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from osgeo import gdal\n",
    "import rasterio\n",
    "\n",
    "# Define the paths to the raster files\n",
    "svi_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/svi_raster.tif'\n",
    "fim_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/fim_raster.tif'\n",
    "aligned_svi_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/aligned_svi_raster.tif'\n",
    "\n",
    "# Open the FIM raster to get the projection, geotransform, and size\n",
    "fim_ds = gdal.Open(fim_raster_path)\n",
    "if fim_ds is None:\n",
    "    raise RuntimeError(f\"Failed to open FIM raster {fim_raster_path}\")\n",
    "\n",
    "fim_proj = fim_ds.GetProjection()\n",
    "fim_geotransform = fim_ds.GetGeoTransform()\n",
    "fim_width = fim_ds.RasterXSize\n",
    "fim_height = fim_ds.RasterYSize\n",
    "\n",
    "print(f\"FIM Raster Properties:\\n CRS: {fim_proj}\\n Geotransform: {fim_geotransform}\\n Width: {fim_width}, Height: {fim_height}\")\n",
    "\n",
    "# Reproject and resample the SVI raster to match the FIM raster\n",
    "warp_options = gdal.WarpOptions(\n",
    "    format='GTiff',\n",
    "    outputBounds=(fim_geotransform[0], fim_geotransform[3] + fim_height * fim_geotransform[5], fim_geotransform[0] + fim_width * fim_geotransform[1], fim_geotransform[3]),\n",
    "    width=fim_width,\n",
    "    height=fim_height,\n",
    "    dstSRS=fim_proj,\n",
    "    xRes=fim_geotransform[1],\n",
    "    yRes=-fim_geotransform[5],\n",
    "    resampleAlg=gdal.GRA_Bilinear,\n",
    "    targetAlignedPixels=True\n",
    ")\n",
    "\n",
    "print(\"Warp options set.\")\n",
    "\n",
    "aligned_svi_raster = gdal.Warp(aligned_svi_raster_path, svi_raster_path, options=warp_options)\n",
    "if aligned_svi_raster is None:\n",
    "    raise RuntimeError(f\"gdal.Warp failed to create {aligned_svi_raster_path}\")\n",
    "\n",
    "print(\"SVI raster has been reprojected and resampled to match the FIM raster.\")\n",
    "\n",
    "# Verify the properties of the aligned SVI raster\n",
    "def check_raster_properties(raster_path):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        print(f\"Properties of {raster_path}:\")\n",
    "        print(f\" CRS: {src.crs}\")\n",
    "        print(f\" Cell size: {src.res}\")\n",
    "        print(f\" Width: {src.width}, Height: {src.height}\")\n",
    "        print(f\" Bounds: {src.bounds}\")\n",
    "        print()\n",
    "\n",
    "# Check properties of the aligned SVI raster\n",
    "check_raster_properties(aligned_svi_raster_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rasterio\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Define the paths to the raster files\n",
    "svi_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/aligned_svi_raster.tif'\n",
    "fim_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/fim_raster.tif'\n",
    "\n",
    "def compute_statistics(raster_path):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        data = src.read(1)\n",
    "        nodata = src.nodata\n",
    "        if nodata is not None:\n",
    "            data = data[data != nodata]  # Remove NoData values\n",
    "        min_val = np.min(data)\n",
    "        max_val = np.max(data)\n",
    "        mean_val = np.mean(data)\n",
    "        std_val = np.std(data)\n",
    "        \n",
    "        return min_val, max_val, mean_val, std_val\n",
    "\n",
    "def plot_histogram(raster_path, title):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        data = src.read(1)\n",
    "        nodata = src.nodata\n",
    "        if nodata is not None:\n",
    "            data = data[data != nodata]  # Remove NoData values\n",
    "        plt.figure(figsize=(10, 6))\n",
    "        plt.hist(data.flatten(), bins=50, color='blue', alpha=0.7)\n",
    "        plt.title(f\"Histogram of {title}\")\n",
    "        plt.xlabel(\"Value\")\n",
    "        plt.ylabel(\"Frequency\")\n",
    "        plt.grid(True)\n",
    "        plt.show()\n",
    "\n",
    "# Compute statistics for SVI raster\n",
    "svi_min, svi_max, svi_mean, svi_std = compute_statistics(svi_raster_path)\n",
    "print(f\"SVI Raster Statistics:\\n Min: {svi_min}\\n Max: {svi_max}\\n Mean: {svi_mean}\\n Std Dev: {svi_std}\")\n",
    "\n",
    "# Compute statistics for FIM raster\n",
    "fim_min, fim_max, fim_mean, fim_std = compute_statistics(fim_raster_path)\n",
    "print(f\"FIM Raster Statistics:\\n Min: {fim_min}\\n Max: {fim_max}\\n Mean: {fim_mean}\\n Std Dev: {fim_std}\")\n",
    "\n",
    "# Plot histograms\n",
    "plot_histogram(svi_raster_path, \"SVI Raster\")\n",
    "plot_histogram(fim_raster_path, \"FIM Raster\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Reclassify fim"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import rasterio\n",
    "\n",
    "def reclassify_fim(input_path, output_path):\n",
    "    with rasterio.open(input_path) as src:\n",
    "        data = src.read(1).astype('float32')\n",
    "        nodata = src.nodata\n",
    "\n",
    "        if nodata is not None:\n",
    "            data = np.ma.masked_equal(data, nodata)\n",
    "        \n",
    "        # Reclassify the FIM data\n",
    "        reclassified_data = np.digitize(data, bins=[0.01, 0.5, 1, 2], right=True)\n",
    "        reclassified_data = np.where(data == 0, 0, reclassified_data)  # Class 0 for non-flooded areas\n",
    "\n",
    "        # Preserve nodata values\n",
    "        reclassified_data = np.ma.filled(reclassified_data, nodata)\n",
    "\n",
    "        meta = src.meta\n",
    "        meta.update(dtype='float32', nodata=-9999)\n",
    "\n",
    "        with rasterio.open(output_path, 'w', **meta) as dst:\n",
    "            dst.write(reclassified_data.astype('float32'), 1)\n",
    "\n",
    "fim_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/fim_raster.tif'\n",
    "reclassified_fim_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/reclassified_fim_raster2.tif'\n",
    "\n",
    "reclassify_fim(fim_raster_path, reclassified_fim_path)\n",
    "print(\"Reclassified FIM raster has been saved.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create impact map"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def multiply_rasters(svi_path, fim_path, output_path):\n",
    "    with rasterio.open(svi_path) as svi_src:\n",
    "        svi_data = svi_src.read(1).astype('float32')\n",
    "        svi_nodata = svi_src.nodata\n",
    "\n",
    "    with rasterio.open(fim_path) as fim_src:\n",
    "        fim_data = fim_src.read(1).astype('float32')\n",
    "        fim_meta = fim_src.meta\n",
    "        fim_nodata = fim_src.nodata\n",
    "\n",
    "    if svi_data.shape != fim_data.shape:\n",
    "        raise ValueError(\"The rasters do not have the same shape.\")\n",
    "\n",
    "    # Ensure that nodata values are handled correctly\n",
    "    nodata_value = -9999\n",
    "    svi_data = np.where(svi_data == svi_nodata, np.nan, svi_data)\n",
    "    fim_data = np.where(fim_data == fim_nodata, np.nan, fim_data)\n",
    "\n",
    "    # Multiply the rasters to get the impact map, ignoring NaN values\n",
    "    impact_data = np.where(np.isnan(svi_data) | np.isnan(fim_data), nodata_value, svi_data * fim_data)\n",
    "\n",
    "    # Save the impact map to a new raster file\n",
    "    impact_meta = fim_meta.copy()\n",
    "    impact_meta.update({\n",
    "        'dtype': 'float32',\n",
    "        'nodata': nodata_value\n",
    "    })\n",
    "\n",
    "    with rasterio.open(output_path, 'w', **impact_meta) as impact_dst:\n",
    "        impact_dst.write(impact_data.astype('float32'), 1)\n",
    "\n",
    "svi_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/aligned_svi_raster.tif'\n",
    "reclassified_fim_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/reclassified_fim_raster2.tif'\n",
    "impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/impact_rastertest.tif'\n",
    "\n",
    "multiply_rasters(svi_raster_path, reclassified_fim_path, impact_raster_path)\n",
    "print(\"Impact map has been saved.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Mask 0s in the impact map"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.colors import Normalize\n",
    "\n",
    "def mask_zeros(input_path, output_path):\n",
    "    with rasterio.open(input_path) as src:\n",
    "        data = src.read(1).astype('float32')\n",
    "        nodata = src.nodata\n",
    "\n",
    "        masked_data = np.where(data == 0, nodata, data)\n",
    "\n",
    "        meta = src.meta\n",
    "        meta.update(dtype='float32', nodata=nodata)\n",
    "\n",
    "        with rasterio.open(output_path, 'w', **meta) as dst:\n",
    "            dst.write(masked_data.astype('float32'), 1)\n",
    "\n",
    "impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/impact_rastertest.tif'\n",
    "masked_impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/masked_impact_raster.tif'\n",
    "\n",
    "mask_zeros(impact_raster_path, masked_impact_raster_path)\n",
    "print(\"Masked impact map has been saved.\")\n",
    "\n",
    "def plot_raster(ax, raster_path, title):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        data = src.read(1)\n",
    "        nodata = src.nodata\n",
    "        if nodata is not None:\n",
    "            data = np.ma.masked_equal(data, nodata)  # Mask NoData values\n",
    "\n",
    "        img = ax.imshow(data, cmap='plasma', norm=Normalize(vmin=data.min(), vmax=data.max()))\n",
    "        ax.set_title(title)\n",
    "        ax.set_xlabel('Longitude')\n",
    "        ax.set_ylabel('Latitude')\n",
    "        return img\n",
    "\n",
    "# Create a figure with subplots\n",
    "fig, ax = plt.subplots(figsize=(10, 10))\n",
    "\n",
    "# Plot the masked impact raster\n",
    "img = plot_raster(ax, masked_impact_raster_path, \"Masked Impact Raster\")\n",
    "\n",
    "# Add colorbars with size control\n",
    "cbar = fig.colorbar(img, ax=ax, fraction=0.046, pad=0.04, shrink=0.4)\n",
    "cbar.set_label('Impact Value')\n",
    "\n",
    "# Adjust layout\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Reclassify the impact map"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import rasterio\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.colors import Normalize\n",
    "\n",
    "def classify_raster(input_path, output_path):\n",
    "    with rasterio.open(input_path) as src:\n",
    "        data = src.read(1).astype('float32')\n",
    "        nodata = src.nodata\n",
    "\n",
    "        # Mask nodata values\n",
    "        data_masked = np.ma.masked_equal(data, nodata)\n",
    "        \n",
    "        # Identify the range of the data excluding nodata values\n",
    "        min_value = data_masked.min()\n",
    "        max_value = data_masked.max()\n",
    "        print(f\"Data range: {min_value} to {max_value}\")\n",
    "\n",
    "        # Classify the data into 4 equal intervals\n",
    "        bins = np.linspace(min_value, max_value, 5)  # 5 bins will create 4 intervals\n",
    "        classified_data = np.digitize(data_masked, bins, right=True)  # Digitize creates 1 to 4 classes\n",
    "\n",
    "        # Convert the classified_data mask to nodata values\n",
    "        classified_data[data_masked.mask] = nodata\n",
    "\n",
    "        print(f\"Classified data range: {np.min(classified_data)} to {np.max(classified_data)}\")\n",
    "\n",
    "        meta = src.meta\n",
    "        meta.update(dtype='float32', nodata=nodata)\n",
    "\n",
    "        with rasterio.open(output_path, 'w', **meta) as dst:\n",
    "            dst.write(classified_data.astype('float32'), 1)\n",
    "\n",
    "masked_impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/masked_impact_raster.tif'\n",
    "classified_impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/classified_impact_raster.tif'\n",
    "\n",
    "classify_raster(masked_impact_raster_path, classified_impact_raster_path)\n",
    "print(\"Classified impact map has been saved.\")\n",
    "\n",
    "def plot_raster(ax, raster_path, title):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        data = src.read(1)\n",
    "        nodata = src.nodata\n",
    "        if nodata is not None:\n",
    "            data = np.ma.masked_equal(data, nodata)  # Mask NoData values\n",
    "\n",
    "        img = ax.imshow(data, cmap='plasma', norm=Normalize(vmin=1, vmax=4))  # Set vmin and vmax to match class values\n",
    "        ax.set_title(title)\n",
    "        ax.set_xlabel('Longitude')\n",
    "        ax.set_ylabel('Latitude')\n",
    "        return img\n",
    "\n",
    "# Create a figure with subplots\n",
    "fig, ax = plt.subplots(figsize=(10, 10))\n",
    "\n",
    "# Plot the classified impact raster\n",
    "img = plot_raster(ax, classified_impact_raster_path, \"Classified Impact Raster\")\n",
    "\n",
    "# Add colorbars with size control\n",
    "cbar = fig.colorbar(img, ax=ax, fraction=0.046, pad=0.04, shrink=0.4)\n",
    "cbar.set_label('Impact Class')\n",
    "\n",
    "# Adjust layout\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import rasterio\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.colors import Normalize\n",
    "\n",
    "# Paths to the raster files\n",
    "fim_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/reclassified_fim_raster2.tif'\n",
    "svi_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N3/aligned_svi_raster.tif'\n",
    "impact_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/classified_impact_raster1.tif'\n",
    "\n",
    "def plot_raster(ax, raster_path, title):\n",
    "    with rasterio.open(raster_path) as src:\n",
    "        data = src.read(1)\n",
    "        nodata = src.nodata\n",
    "        if nodata is not None:\n",
    "            data = np.ma.masked_equal(data, nodata)  # Mask NoData values\n",
    "\n",
    "        img = ax.imshow(data, cmap='plasma', norm=Normalize(vmin=data.min(), vmax=data.max()))\n",
    "        ax.set_title(title)\n",
    "        ax.set_xlabel('Longitude')\n",
    "        ax.set_ylabel('Latitude')\n",
    "        return img\n",
    "\n",
    "# Create a figure with subplots\n",
    "fig, axes = plt.subplots(1, 3, figsize=(30, 10))\n",
    "\n",
    "# Plot the FIM raster\n",
    "img1 = plot_raster(axes[0], fim_raster_path, \"FIM Raster\")\n",
    "\n",
    "# Plot the SVI raster\n",
    "img2 = plot_raster(axes[1], svi_raster_path, \"SVI Raster\")\n",
    "\n",
    "# Plot the impact raster\n",
    "img3 = plot_raster(axes[2], impact_raster_path, \"Impact Raster\")\n",
    "\n",
    "# Add colorbars with size control\n",
    "cbar1 = fig.colorbar(img1, ax=axes[0], fraction=0.046, pad=0.04, shrink=0.4)\n",
    "cbar1.set_label('Value')\n",
    "\n",
    "cbar2 = fig.colorbar(img2, ax=axes[1], fraction=0.046, pad=0.04, shrink=0.4)\n",
    "cbar2.set_label('Value')\n",
    "\n",
    "cbar3 = fig.colorbar(img3, ax=axes[2], fraction=0.046, pad=0.04, shrink=0.4)\n",
    "cbar3.set_label('Value')\n",
    "\n",
    "# Adjust layout\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make shapefile"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from osgeo import gdal, ogr\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "def raster_to_shapefile(raster_path, shapefile_path):\n",
    "    # Open the reclassified raster\n",
    "    src_ds = gdal.Open(raster_path)\n",
    "    if src_ds is None:\n",
    "        raise RuntimeError(f\"Failed to open raster {raster_path}\")\n",
    "    \n",
    "    # Get the raster band\n",
    "    src_band = src_ds.GetRasterBand(1)\n",
    "    nodata = src_band.GetNoDataValue()\n",
    "    \n",
    "    # Create the output shapefile\n",
    "    driver = ogr.GetDriverByName('ESRI Shapefile')\n",
    "    if driver is None:\n",
    "        raise RuntimeError(\"ESRI Shapefile driver not available.\")\n",
    "    \n",
    "    dst_ds = driver.CreateDataSource(shapefile_path)\n",
    "    if dst_ds is None:\n",
    "        raise RuntimeError(f\"Failed to create shapefile {shapefile_path}\")\n",
    "    \n",
    "    srs = ogr.osr.SpatialReference()\n",
    "    srs.ImportFromWkt(src_ds.GetProjection())\n",
    "    \n",
    "    dst_layer = dst_ds.CreateLayer('impact', srs=srs, geom_type=ogr.wkbPolygon)\n",
    "    if dst_layer is None:\n",
    "        raise RuntimeError(f\"Failed to create layer in shapefile {shapefile_path}\")\n",
    "    \n",
    "    field_defn = ogr.FieldDefn('FIV_Class', ogr.OFTInteger)\n",
    "    dst_layer.CreateField(field_defn)\n",
    "    \n",
    "    # Polygonize the raster, skipping NoData values\n",
    "    gdal.Polygonize(src_band, src_band.GetMaskBand(), dst_layer, 0, options=[\"8CONNECTED=8\"], callback=None)\n",
    "    \n",
    "    # Remove features with the NoData value\n",
    "    dst_layer.SetAttributeFilter(f\"FIV_Class = {int(nodata)}\")\n",
    "    for feature in dst_layer:\n",
    "        dst_layer.DeleteFeature(feature.GetFID())\n",
    "    dst_layer.SetAttributeFilter(None)\n",
    "    \n",
    "    # Close the datasets\n",
    "    src_ds = None\n",
    "    dst_ds = None\n",
    "\n",
    "# Path to the reclassified impact raster file\n",
    "reclassified_raster_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/classified_impact_raster1.tif'\n",
    "shapefile_path = r'D:/Hesham/CUAHSI/Geospatial/Jupyter N4/reclassified_impact_raster.shp'\n",
    "\n",
    "\n",
    "# Convert the reclassified raster to a shapefile\n",
    "raster_to_shapefile(reclassified_raster_path, shapefile_path)\n",
    "print(\"Shapefile has been created.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "add column to attribute table of FIV map to describe the severity of the vulnerability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from osgeo import ogr\n",
    "\n",
    "def add_vulnerability_column(shapefile_path):\n",
    "    # Open the shapefile\n",
    "    driver = ogr.GetDriverByName('ESRI Shapefile')\n",
    "    ds = driver.Open(shapefile_path, 1)  # Open in write mode\n",
    "    if ds is None:\n",
    "        raise RuntimeError(f\"Failed to open shapefile {shapefile_path}\")\n",
    "    \n",
    "    layer = ds.GetLayer()\n",
    "    \n",
    "    # Add new field for vulnerability levels\n",
    "    vulnerability_field = ogr.FieldDefn('Vuln_Level', ogr.OFTString)\n",
    "    vulnerability_field.SetWidth(32)\n",
    "    layer.CreateField(vulnerability_field)\n",
    "    \n",
    "    # Define the vulnerability levels\n",
    "    vulnerability_levels = {\n",
    "        1: \"Low Vulnerability\",\n",
    "        2: \"Medium Vulnerability\",\n",
    "        3: \"High Vulnerability\",\n",
    "        4: \"Very High Vulnerability\"    \n",
    "    }\n",
    "    \n",
    "    # Update the new field based on FIV_Class\n",
    "    for feature in layer:\n",
    "        fiv_class = feature.GetField('FIV_Class')\n",
    "        vulnerability_level = vulnerability_levels.get(fiv_class, \"Unknown\")\n",
    "        feature.SetField('Vuln_Level', vulnerability_level)\n",
    "        layer.SetFeature(feature)\n",
    "    \n",
    "    # Close the dataset\n",
    "    ds = None\n",
    "    print(\"Vulnerability level column has been added to the shapefile.\")\n",
    "\n",
    "# Path to the shapefile\n",
    "shapefile_path = infolder+'ImpactMap.shp'\n",
    "\n",
    "# Add the vulnerability level column\n",
    "add_vulnerability_column(shapefile_path)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Convert to geojson and commit to github"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert to GeoJSON\n",
    "\n",
    "# Step 1: Load the shapefile\n",
    "gdf = gpd.read_file(shapefile_path)\n",
    "\n",
    "# Step 2: Convert to GeoJSON\n",
    "geojson_str = gdf.to_json()\n",
    "\n",
    "# Step 3: Save the GeoJSON to a file\n",
    "output_path = infolder+'ImpactMap.geojson'  # Replace with your desired output file name\n",
    "with open(output_path, 'w') as f:\n",
    "    f.write(geojson_str)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
